import { readFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

/** Accepted input keys for one fal model, distilled from its OpenAPI spec. */
export interface FalInputKeys {
  /** Top-level property names on the model's input schema. */
  top: string[];
  /** Dotted paths of nested object properties, e.g. `audio_setting.format`. */
  nested: string[];
}

export type FalInputKeyMap = Record<string, FalInputKeys>;

let cached: FalInputKeyMap | null | undefined;

const __dirname = dirname(fileURLToPath(import.meta.url));
const DEFAULT_PATH = resolve(__dirname, 'fal-input-keys.json');

/**
 * Load the distilled fal input-key map.
 *
 * Generated by `scripts/build-fal-input-keys.mjs` from the committed
 * OpenAPI specs and refreshed by the weekly drift cron. Lives beside
 * `models.json` so tsup's copy step puts it in `dist/` where `__dirname`
 * resolves at runtime.
 *
 * Returns `null` if the file is missing or unreadable. Callers must treat
 * that as "cannot check" and stay silent — this data only ever powers
 * warnings, so a missing file must never become an error or a false
 * alarm.
 */
export async function loadFalInputKeys(
  path: string = DEFAULT_PATH,
): Promise<FalInputKeyMap | null> {
  if (cached !== undefined) return cached;
  try {
    cached = JSON.parse(await readFile(path, 'utf8')) as FalInputKeyMap;
  } catch {
    cached = null;
  }
  return cached;
}

/** Test-only cache reset. */
export function __resetFalInputKeysCacheForTests(): void {
  cached = undefined;
}
